### ISSUE TITLE
Toggle colums in list does not work

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#503]
**To Reproduce**
Try to hide a column in a list with Toggle Columns

**Expected behavior**
Selected Column(s) become invisible

**Actual behavior**
Column(s) still visible

**Screenshots**

**Additional context**

**Comment by skurvish** [comment]
Looks like the toggle code needs BS5 styling.

**Comment by trob** [comment]
Fixes with https://github.com/joomlahenk/fabrik/pull/504

**Comment by skurvish** [comment]
PR #506 fixes the alignment of the toggle button.

**Comment by skurvish** [comment]
@EricdeWaal can you confirm this is fixed please.

**Comment by EricdeWaal** [comment]
Could you get me the modified file(s), so I can test again?
​Or is there an easier way like a direct update from the repo?

Op 8 nov. 2022 01:04, om 01:04, skurvish ***@***.***> schreef:
***@***.*** can you confirm this is fixed please.

**Comment by skurvish** [comment]
Please see this [wiki page](https://github.com/joomlahenk/fabrik/wiki/Testing-a-fix)

**Comment by trob** [comment]
The related PRs are https://github.com/joomlahenk/fabrik/pull/504, https://github.com/joomlahenk/fabrik/pull/506
(and https://github.com/joomlahenk/fabrik/pull/513 for the minified file)

**Comment by EricdeWaal** [comment]
I have replaced the 3 files from #504, #506 and #513
The alignment is still not good; a padding-top of 8px was added, in order to align it with the items right of it, that should be 11px and the 8px on line 33 can be omitted.

The toggle itself does not work yet. It seems to have 3 states now:
![afbeelding](https://user-images.githubusercontent.com/5586423/200603056-200ab4c7-1b5a-4119-8446-aab5e462f5a0.png)
The first one (Joomla gegevens) is as the dropdown opens
The second one (Joomla ID) is after clicking it once
The third (Datum aangemeld) is after a second click.
The columns are shown all the time

**Comment by skurvish** [comment]
So, are you saying all is well with the non-minified js files?

**Comment by trob** [comment]
It's working fine on my site with the minified file (from PR 513).
Did you clear Joomla and browser cache? or enable "burst" in Fabrik Debugging options (to force the js files be loaded again)?

**Comment by EricdeWaal** [comment]
> So, are you saying all is well with the non-minified js files?

Yes, then it works as expected.

**Comment by EricdeWaal** [comment]
> It's working fine on my site with the minified file (from PR 513). Did you clear Joomla and browser cache? or enable "burst" in Fabrik Debugging options (to force the js files be loaded again)?

I found it. I replaced the minified file media/com_fabrik/js/list-toggle-min.js while I should have put the new minified file content in media/com_fabrik/js/dist/list-toggle.js. A second version of the same file, minified but no '-min' in the file name?

**Comment by skurvish** [comment]
Yes, for whatever reason the original developers didn't add the -min to the filename, just minified and placed them in the dist folder.

**Comment by EricdeWaal** [comment]
OK, has the alignment been fixed? 
See "The alignment is still not good; a padding-top of 8px was added, in order to align it with the items right of it, that should be 11px and the 8px on line 33 can be omitted."

**Comment by trob** [comment]
I'll have a look at the alignement.
I think we should not "paint" by adding some "hardcoded" px - other templates may have different paddings etc.

(But some px don't have the highest prio ;-) )

**Comment by trob** [comment]
PR https://github.com/joomlahenk/fabrik/pull/517

**Comment by EricdeWaal** [comment]
Confirmation: Solved
